import 'package:flutter/material.dart';

class AppColors {
  static const primary = Color(0xffE91A20);
  static const transparent = Colors.transparent;
  static const white = Color(0xffffffff);
  static const grey = Colors.grey;
  static const halfWhite = Color(0x80ffffff);
  static const black = Color(0xff000000);
  static const applyNewStationIconColor = Color(0xffeaf1fc);
  static const redLocationIconColor = Color(0xfffdf0ef);
  static const lightGrey = Color(0xfff0f0f0);
  static const inactiveColor = Color(0xffb3b3b3);
  static const textFieldLabelColor = Color(0xff6C7278);
  static const subHeadingColor = Color(0xff666666);
  static const actionContainerColor = Color(0xfff5f5f5);
  static const extraInformationColor = Color(0xff999999);
  static const whiteGreyColor = Color(0xfff0f0f0);
  static const black2Color = Color(0xff1A1A1A);
  static const nextStep1Color = Color(0xff0057D9);
  static const nextStep2Color = Color(0xff1FB996);
  static const nextStep3Color = Color(0xffF5A623);
  static const emailUsIconColor = Color(0xffE84C3D);
  static const scaffoldBackgroundColor = Color(0xffF4F4F4);
  static const headerDarkBlueColor = Color(0xff003C9E);
  static const inProcessCountColor = Color(0xffF5A623);
  static const inProcessCountDarkColor = Color(0xffE89917);
  static const inauguratedCountColor = Color(0xff1FB996);
  static const inauguratedCountDarkColor = Color(0xff189980);
  static const rejectedCountColor = Color(0xffE84C3D);
  static const rejectedCountDarkColor = Color(0xffD43D2F);
  static const expandIconColor = Color(0xffCCCCCC);
  static const commissioningColor = Color(0xff9B59B6);
  static const inactiveStatusColor = Color(0xffE0E0E0);
  static const onlineStatusColor =  Color(0xFF10B981);
  static const offlineStatusColor =  Color(0xFFFF8C42);
  static const syncedCountColor =  Color(0xFF2196F3);
  static const shimmerBaseColor =  Color(0xFFE0E0E0);
  static const shimmerHighlightColor =  Color(0xFFF5F5F5);
}
